<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Clientes.aspx.vb" Inherits="Clientes" %>

<!DOCTYPE html>
<html>
<head runat="server">
    <title>CRUD de Clientes</title>
</head>
<body>
    <form id="form1" runat="server">
        <div style="width: 800px; margin: 20px auto; font-family: Arial;">
            <h2>Administración de Clientes</h2>

            <asp:Panel ID="pnlForm" runat="server" DefaultButton="btnGuardar">
                <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                        <td><asp:Label ID="Label1" runat="server" Text="Nombre:" AssociatedControlID="txtNombre" /></td>
                        <td>
                            <asp:TextBox ID="txtNombre" runat="server" Width="200px"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvNombre" runat="server" ControlToValidate="txtNombre"
                                ErrorMessage="Nombre es obligatorio" ForeColor="Red" Display="Dynamic" />
                        </td>
                    </tr>
                    <tr>
                        <td><asp:Label ID="Label2" runat="server" Text="Apellidos:" AssociatedControlID="txtApellidos" /></td>
                        <td>
                            <asp:TextBox ID="txtApellidos" runat="server" Width="200px"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvApellidos" runat="server" ControlToValidate="txtApellidos"
                                ErrorMessage="Apellidos son obligatorios" ForeColor="Red" Display="Dynamic" />
                        </td>
                    </tr>
                    <tr>
                        <td><asp:Label ID="Label3" runat="server" Text="Teléfono:" AssociatedControlID="txtTelefono" /></td>
                        <td>
                            <asp:TextBox ID="txtTelefono" runat="server" Width="200px"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvTelefono" runat="server" ControlToValidate="txtTelefono"
                                ErrorMessage="Teléfono es obligatorio" ForeColor="Red" Display="Dynamic" />
                        </td>
                    </tr>
                    <tr>
                        <td><asp:Label ID="Label4" runat="server" Text="Email:" AssociatedControlID="txtEmail" /></td>
                        <td>
                            <asp:TextBox ID="txtEmail" runat="server" Width="200px"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvEmail" runat="server" ControlToValidate="txtEmail"
                                ErrorMessage="Email es obligatorio" ForeColor="Red" Display="Dynamic" />
                            <asp:RegularExpressionValidator ID="revEmail" runat="server" ControlToValidate="txtEmail"
                                ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"
                                ErrorMessage="Email no válido" ForeColor="Red" Display="Dynamic" />
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <asp:Button ID="btnGuardar" runat="server" Text="Guardar" OnClick="btnGuardar_Click" />
                            <asp:Button ID="btnCancelar" runat="server" Text="Cancelar" OnClick="btnCancelar_Click" />
                        </td>
                    </tr>
                </table>
            </asp:Panel>

            <hr />

            <h3>Clientes</h3>
            <asp:GridView ID="gvClientes" runat="server" AutoGenerateColumns="False" 
                DataKeyNames="ClienteId" OnSelectedIndexChanged="gvClientes_SelectedIndexChanged"
                OnRowDeleting="gvClientes_RowDeleting" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True"
                Width="100%">
                <Columns>
                    <asp:BoundField DataField="ClienteId" HeaderText="ID" ReadOnly="True" />
                    <asp:BoundField DataField="Nombre" HeaderText="Nombre" />
                    <asp:BoundField DataField="Apellidos" HeaderText="Apellidos" />
                    <asp:BoundField DataField="Telefono" HeaderText="Teléfono" />
                    <asp:BoundField DataField="Email" HeaderText="Email" />
                </Columns>
            </asp:GridView>

            <asp:Label ID="lblMensaje" runat="server" ForeColor="Green" EnableViewState="false" />

        </div>
    </form>
</body>
</html>
